version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"  # Map host 3000 to container 3000
    networks:
      - app-network
    volumes:
      - ./cert:/app/cert
      - ./frontend:/app
      - /app/node_modules
      # - ./frontend/dist:/app/dist
    depends_on:
      - backend
    env_file:
      ./.env
    working_dir: /app
    container_name: frontend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/sqlite3.db:/app/sqlite3.db 
      - ./cert:/app/cert
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    env_file:
      ./.env
    working_dir: /app
    container_name: backend
networks:
  app-network:
    driver: bridge
