version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    container_name: frontend
  auth-service:
    build:
      context: .
      dockerfile: ./backend/auth-service/Dockerfile
    working_dir: /app
    container_name: auth-service
  # database:
  #   build:
  #     context: .
  #     dockerfile: ./backend/database/Dockerfile
  #   container_name: database
  #   depends_on:
  #     - frontend
  # volume:
  #   frontend: 
    # depends_on:
    #   - database
  # user-service:
  #   build:
  #     context: .
  #     Dockerfile: ./backend/user-service/Dockerfile
  #   container_name: user-service
  #   depends_on:
  #     - database
