FROM node:18

WORKDIR /app

# RUN npm install
# RUN npm install -D vite tailwindcss postcss autoprefixer
# RUN npm init
CMD ["npm", "init"]
# COPY /backend/certificates/ /app/certificates/
# COPY ./backend/auth-service ./
# COPY ./frontend/ .

EXPOSE 3000

